jobs:
  job_id:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/419266631077/locations/global/workloadIdentityPools/github-wif-pool/providers/githubwif'
        service_account: 'server@bankstatementparser-dev.iam.gserviceaccount.com'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v1'
      with:
        name: 'bank-statement-parser'
        runtime: 'nodejs16'
