name: cloud-function-deploy

on:
  push:
    branches:
    - 'main'
    paths:
    - 'parser/functions/**'
    - '.github/workflows/parser.yml'

jobs:
  cloud-fn-deploy:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/419266631077/locations/global/workloadIdentityPools/github-wif-pool/providers/githubwif'
        service_account: 'server@bankstatementparser-dev.iam.gserviceaccount.com'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v1'
      with:
        name: 'bank-statement-parser'
        runtime: 'python310'
        entry_point: 'process_bank_statement_pdf'
        region: 'asia-south1'
        source_dir: 'parser/functions'
        event_trigger_type: providers/cloud.storage/eventTypes/object.change
        event_trigger_resource: projects/_/buckets/bank-statement-parser-dev-user-data
        secret_environment_variables: 'MONGODB_PWD=projects/419266631077/secrets/mongodb-atlas-db-pwd/versions/latest'
